// Copyright 2026 Robert Macrae. All rights reserved.
// SPDX-License-Identifier: LicenseRef-Proprietary

import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service - OrcaBot",
  description: "Orcabot Terms of Service",
};

export default function TermsOfServicePage() {
  return (
    <>
      <h1>Terms of Service</h1>
      <p className="subtitle">
        <strong>Effective Date:</strong> February 8, 2026 &middot; <strong>Last Updated:</strong> February 8, 2026
      </p>
      <p>
        These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and use of Orcabot
        (&ldquo;Service,&rdquo; &ldquo;Platform,&rdquo; or &ldquo;we&rdquo;), a sandboxed AI coding
        platform operated by Rob Macrae (&ldquo;Company,&rdquo; &ldquo;we,&rdquo;
        &ldquo;us,&rdquo; or &ldquo;our&rdquo;). By accessing or using the Service, you agree to be
        bound by these Terms. If you do not agree, do not use the Service.
      </p>

      {/* Section 1 */}
      <h2>1. Definitions</h2>
      <ul>
        <li><strong>&ldquo;Account&rdquo;</strong> means your registered Orcabot account.</li>
        <li>
          <strong>&ldquo;AI Provider&rdquo;</strong> means any third-party artificial intelligence
          service (e.g., Anthropic, OpenAI, Google) whose API keys you supply to the Platform.
        </li>
        <li>
          <strong>&ldquo;Customer Content&rdquo;</strong> means all data, code, files, prompts,
          configurations, and other materials you create, upload, or generate through the Service,
          including AI-generated outputs.
        </li>
        <li>
          <strong>&ldquo;Dashboard&rdquo;</strong> means a collaborative workspace you create or are
          invited to on the Platform.
        </li>
        <li>
          <strong>&ldquo;Integration&rdquo;</strong> means a third-party service (e.g., Gmail,
          GitHub, Google Drive, Slack) connected to the Platform via OAuth or other authorization
          mechanisms.
        </li>
        <li>
          <strong>&ldquo;Sandbox&rdquo;</strong> means the isolated virtual machine environment in
          which code and AI agents execute on the Platform.
        </li>
        <li>
          <strong>&ldquo;Secrets&rdquo;</strong> means API keys, tokens, credentials, and other
          sensitive values you store through the Platform&apos;s secrets broker.
        </li>
        <li>
          <strong>&ldquo;Usage Data&rdquo;</strong> means data about how you interact with the
          Platform (e.g., feature usage, performance metrics, error logs), distinct from Customer
          Content.
        </li>
      </ul>

      {/* Section 2 */}
      <h2>2. Account and Eligibility</h2>
      <p>
        2.1. You must be at least 18 years old (or the age of majority in your jurisdiction) to use
        the Service.
      </p>
      <p>
        2.2. You must authenticate via a supported identity provider (currently Google). You are
        responsible for maintaining the security of your account and all activity under it.
      </p>
      <p>
        2.3. You may not share your account credentials. If you become aware of unauthorized access,
        you must notify us immediately.
      </p>

      {/* Section 3 */}
      <h2>3. The Service</h2>
      <p>
        3.1. <strong>Platform, Not AI Provider.</strong> Orcabot provides an execution environment
        for AI coding agents, collaborative dashboards, and integration management.{" "}
        <strong>Orcabot is not an AI provider.</strong> When you supply your own API keys and run AI
        agents (Claude Code, Codex, Gemini CLI, or others), the AI service relationship is directly
        between you and that AI Provider. Orcabot facilitates execution but does not control,
        endorse, or guarantee AI outputs.
      </p>
      <p>
        3.2. <strong>Sandboxed Execution.</strong> The Platform runs code in sandboxed virtual
        machines designed to provide isolation. Sandboxing is provided on a{" "}
        <strong>best-effort basis</strong> and is not a guarantee against all forms of data leakage,
        resource exhaustion, or unintended behavior. You are solely responsible for all code you
        execute, whether written by you or generated by an AI agent.
      </p>
      <p>
        3.3. <strong>Secrets Broker.</strong> The Platform provides a secrets broker to manage API
        keys and credentials. Orcabot acts as a <strong>custodian</strong> of your Secrets, using
        them solely to provide the Service. We do not use your API keys for any purpose other than
        executing requests you authorize. You are responsible for the validity, permissions, and
        costs associated with your API keys.
      </p>
      <p>
        3.4. <strong>Integrations.</strong> When you connect third-party Integrations (Gmail, GitHub,
        Google Drive, Calendar, Slack, etc.), you authorize Orcabot to act as an intermediary
        executing requests on your behalf according to policies you define. Orcabot enforces a
        fail-closed security model: if a policy is missing, ambiguous, or expired, access is denied.
      </p>
      <p>
        3.5. <strong>Multiplayer Collaboration.</strong> Dashboards support real-time multiplayer
        collaboration. The Dashboard owner controls access, integration connections, and policies. By
        joining a Dashboard, collaborators agree that the owner administers the workspace and its
        content.
      </p>
      <p>
        3.6. <strong>Availability.</strong> We may modify, suspend, or discontinue any part of the
        Service at any time. We may terminate or restart Sandbox environments for maintenance,
        security, or resource management. We will make reasonable efforts to provide notice of
        material changes.
      </p>

      {/* Section 4 */}
      <h2>4. Your Responsibilities</h2>
      <p>
        4.1. <strong>Compliance with Third-Party Terms.</strong> You must comply with the terms of
        service, acceptable use policies, and usage limits of:
      </p>
      <ul>
        <li>
          Your AI Provider(s) (e.g., Anthropic&apos;s Terms, OpenAI&apos;s Usage Policies,
          Google&apos;s Generative AI Terms)
        </li>
        <li>
          Any Integrations you connect (e.g., Google API Services User Data Policy, GitHub Terms)
        </li>
        <li>Applicable laws and regulations in your jurisdiction</li>
      </ul>
      <p>
        4.2. <strong>AI Output Review.</strong> AI-generated code and content may contain bugs,
        security vulnerabilities, license-incompatible code, inaccuracies, or harmful content.{" "}
        <strong>
          You are solely responsible for reviewing, testing, and validating all AI-generated output
          before use, deployment, or distribution.
        </strong>{" "}
        Do not rely on AI output for medical, legal, financial, or safety-critical applications
        without independent professional verification.
      </p>
      <p>
        4.3. <strong>Integration Actions.</strong> When AI agents perform actions through connected
        Integrations (sending emails, creating GitHub issues, modifying files, etc.),{" "}
        <strong>you are responsible for those actions</strong> as if you had performed them manually.
        You must configure appropriate policies to control agent behavior.
      </p>
      <p>
        4.4. <strong>Backups.</strong> Persistent workspace data is provided on a best-effort basis.
        You are responsible for maintaining your own backups of important code and data. We are not
        liable for data loss due to Sandbox termination, infrastructure failures, or account
        deletion.
      </p>
      <p>
        4.5. <strong>Security.</strong> You are responsible for the security of your API keys, OAuth
        tokens, and account access. Do not share credentials. Report suspected security incidents to
        us promptly.
      </p>

      {/* Section 5 */}
      <h2>5. Prohibited Uses</h2>
      <p>You may not use the Service to:</p>
      <p>5.1. Violate any applicable law, regulation, or third-party rights.</p>
      <p>
        5.2. Generate, store, or distribute child sexual abuse material or content that exploits
        minors.
      </p>
      <p>
        5.3. Facilitate violence, terrorism, harassment, or threats against any person or group.
      </p>
      <p>
        5.4. Develop malware, ransomware, or tools designed for unauthorized access to systems.
      </p>
      <p>
        5.5. Circumvent or attempt to circumvent the Platform&apos;s security measures, sandboxing,
        secrets broker protections, or rate limits.
      </p>
      <p>
        5.6. Use the Service to attack, disrupt, or degrade third-party services, including through
        the abuse of connected Integrations.
      </p>
      <p>
        5.7. Engage in automated scraping, credential stuffing, or denial-of-service attacks against
        the Platform or through the Platform.
      </p>
      <p>
        5.8. Resell, sublicense, or provide access to the Service to third parties without our
        written consent.
      </p>
      <p>
        5.9. Use the Service in a manner that could create liability for us or impair the Service for
        other users.
      </p>
      <p>
        5.10. Misrepresent AI-generated content as solely human-created in contexts where such
        disclosure is legally required.
      </p>

      {/* Section 6 */}
      <h2>6. Intellectual Property</h2>
      <p>
        6.1. <strong>Your Content.</strong> You retain all rights to your Customer Content. We claim
        no ownership over your code, files, prompts, or AI-generated outputs. We use Customer
        Content solely to provide and improve the Service.
      </p>
      <p>
        6.2. <strong>Our Platform.</strong> We retain all rights to the Orcabot Platform, including
        its software, design, trademarks, and documentation. These Terms do not grant you any rights
        to our intellectual property except the limited right to use the Service.
      </p>
      <p>
        6.3. <strong>AI Output Ownership.</strong> Ownership of AI-generated output is governed by
        your agreement with your AI Provider and applicable law. Orcabot makes no representations
        regarding your rights in AI-generated content. You are responsible for determining what
        rights, if any, you hold in such output.
      </p>
      <p>
        6.4. <strong>Feedback.</strong> If you provide suggestions, feature requests, or other
        feedback about the Service, we may use it without restriction or compensation.
      </p>

      {/* Section 7 */}
      <h2>7. Data Handling</h2>
      <p>
        7.1. <strong>No Model Training.</strong> Orcabot does not train AI models. We do not use your
        Customer Content, code, prompts, or AI outputs to train or fine-tune any machine learning
        model. Whether your AI Provider uses your data for training is governed by your agreement
        with that provider.
      </p>
      <p>
        7.2. <strong>Usage Data.</strong> We collect Usage Data (feature usage patterns, performance
        metrics, error rates) to operate and improve the Platform. Usage Data is distinct from
        Customer Content and does not include the substance of your code, prompts, or outputs.
      </p>
      <p>
        7.3. <strong>Data Processing.</strong> Our handling of personal data is described in our{" "}
        <Link href="/privacy">Privacy Policy</Link>. By using the Service, you acknowledge that you
        have read and understood our Privacy Policy.
      </p>

      {/* Section 8 */}
      <h2>8. Payment and Billing</h2>
      <p>
        8.1. Certain features of the Service may require a paid subscription. Fees are described on
        our pricing page and are non-refundable except as required by law.
      </p>
      <p>
        8.2. We may change pricing with 30 days&apos; notice. Continued use after a price change
        constitutes acceptance.
      </p>
      <p>
        8.3. You are solely responsible for all costs incurred through your AI Provider API keys,
        including charges from AI providers for tokens, compute, and API calls made through the
        Platform.
      </p>

      {/* Section 9 */}
      <h2>9. Disclaimers</h2>
      <div className="caps-section">
        <p>
          9.1. <strong>AS-IS BASIS.</strong> THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND
          &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED,
          STATUTORY, OR OTHERWISE. WE DISCLAIM ALL IMPLIED WARRANTIES, INCLUDING WARRANTIES OF
          MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.
        </p>
        <p>
          9.2. <strong>NO GUARANTEE OF AI OUTPUTS.</strong> WE DO NOT WARRANT THAT AI-GENERATED
          OUTPUTS WILL BE ACCURATE, COMPLETE, NON-INFRINGING, SECURE, OR FIT FOR ANY PARTICULAR
          PURPOSE. AI OUTPUTS MAY CONTAIN ERRORS, VULNERABILITIES, OR LICENSE-INCOMPATIBLE CODE.
        </p>
        <p>
          9.3. <strong>NO GUARANTEE OF ISOLATION.</strong> WE DO NOT WARRANT THAT SANDBOX
          ENVIRONMENTS ARE IMPENETRABLE OR THAT SECRETS BROKER PROTECTIONS WILL PREVENT ALL POSSIBLE
          EXFILTRATION. SECURITY IS PROVIDED ON A BEST-EFFORT BASIS USING INDUSTRY-STANDARD
          PRACTICES.
        </p>
        <p>
          9.4. <strong>NO GUARANTEE OF AVAILABILITY.</strong> WE DO NOT WARRANT UNINTERRUPTED,
          ERROR-FREE, OR SECURE ACCESS TO THE SERVICE. SANDBOX ENVIRONMENTS MAY BE TERMINATED,
          RESTARTED, OR MIGRATED AT ANY TIME.
        </p>
        <p>
          9.5. <strong>THIRD-PARTY SERVICES.</strong> WE ARE NOT RESPONSIBLE FOR THE AVAILABILITY,
          ACCURACY, OR CONDUCT OF THIRD-PARTY AI PROVIDERS, INTEGRATION SERVICES, OR ANY CONTENT
          ACCESSED THROUGH THEM.
        </p>
        <p>
          9.6. <strong>BETA FEATURES.</strong> FEATURES LABELED AS &ldquo;BETA,&rdquo;
          &ldquo;PREVIEW,&rdquo; OR &ldquo;EXPERIMENTAL&rdquo; ARE PROVIDED WITHOUT ANY WARRANTY OR
          SUPPORT COMMITMENT AND MAY BE MODIFIED OR REMOVED AT ANY TIME.
        </p>
      </div>

      {/* Section 10 */}
      <h2>10. Limitation of Liability</h2>
      <div className="caps-section">
        <p>
          10.1. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL ORCABOT, ITS AFFILIATES,
          OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
          CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO DAMAGES FOR
          LOSS OF PROFITS, DATA, GOODWILL, USE, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR
          RELATING TO YOUR USE OF OR INABILITY TO USE THE SERVICE, REGARDLESS OF THE THEORY OF
          LIABILITY AND EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
        </p>
        <p>
          10.2. OUR TOTAL AGGREGATE LIABILITY FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THESE
          TERMS OR THE SERVICE SHALL NOT EXCEED THE GREATER OF: (A) THE AMOUNTS YOU PAID TO US IN
          THE TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM, OR (B) ONE HUNDRED
          U.S. DOLLARS ($100).
        </p>
        <p>10.3. WITHOUT LIMITING THE FOREGOING, WE SHALL HAVE NO LIABILITY FOR:</p>
        <ul>
          <li>
            (a) Actions taken by AI agents through connected Integrations, including emails sent,
            code committed, files modified, or any other automated actions;
          </li>
          <li>
            (b) Costs, charges, or overages incurred with your AI Provider or other third-party
            services;
          </li>
          <li>(c) Loss or corruption of data in Sandbox workspaces;</li>
          <li>
            (d) Security incidents arising from your API keys, credentials, or account compromise;
          </li>
          <li>
            (e) Content generated by AI agents, including code that infringes third-party
            intellectual property, contains vulnerabilities, or causes harm when deployed;
          </li>
          <li>(f) Actions or omissions of other users in shared Dashboards.</li>
        </ul>
      </div>
      <p>
        10.4. The limitations in this section apply to the fullest extent permitted by applicable
        law, even if a remedy fails of its essential purpose.
      </p>

      {/* Section 11 */}
      <h2>11. Indemnification</h2>
      <p>
        11.1.{" "}
        <strong>
          You agree to indemnify, defend, and hold harmless Orcabot and its affiliates, officers,
          directors, employees, and agents from and against any claims, liabilities, damages, losses,
          costs, and expenses (including reasonable attorney&apos;s fees) arising out of or relating
          to:
        </strong>
      </p>
      <ol type="a">
        <li>(a) Your use of the Service or any activity under your account;</li>
        <li>(b) Customer Content you create, upload, or generate through the Service;</li>
        <li>
          (c) Actions taken by AI agents operating under your account or API keys, including actions
          through connected Integrations;
        </li>
        <li>(d) Your violation of these Terms, any third-party terms, or applicable law;</li>
        <li>(e) Your negligence or willful misconduct;</li>
        <li>
          (f) Any claim by a third party arising from code, content, or communications generated or
          transmitted through your use of the Service.
        </li>
      </ol>
      <p>
        11.2. We will provide you with prompt notice of any such claim and reasonable cooperation in
        the defense. You may not settle any claim that imposes obligations on us without our prior
        written consent.
      </p>

      {/* Section 12 */}
      <h2>12. Termination</h2>
      <p>12.1. You may terminate your account at any time by contacting us.</p>
      <p>
        12.2. We may suspend or terminate your account at any time for any reason, including
        violation of these Terms, with or without notice.
      </p>
      <p>
        12.3. Upon termination: (a) your right to use the Service ceases immediately; (b) we may
        delete your Customer Content and Sandbox data after a reasonable retention period (currently
        30 days); (c) Secrets stored through the broker will be deleted; (d) provisions that by
        their nature should survive (including Sections 6, 9, 10, 11, and 13) will survive
        termination.
      </p>

      {/* Section 13 */}
      <h2>13. General</h2>
      <p>
        13.1. <strong>Governing Law.</strong> These Terms are governed by the laws of the State of
        California, without regard to conflict of law principles.
      </p>
      <p>
        13.2. <strong>Dispute Resolution.</strong> Any disputes arising under these Terms shall be
        resolved through binding arbitration in accordance with the rules of JAMS,
        except that either party may seek injunctive relief in any court of competent jurisdiction.
      </p>
      <p>
        13.3. <strong>Entire Agreement.</strong> These Terms, together with the Privacy Policy and
        any applicable order forms, constitute the entire agreement between you and Orcabot.
      </p>
      <p>
        13.4. <strong>Severability.</strong> If any provision is held unenforceable, the remaining
        provisions continue in full force.
      </p>
      <p>
        13.5. <strong>No Waiver.</strong> Our failure to enforce any right or provision does not
        constitute a waiver.
      </p>
      <p>
        13.6. <strong>Assignment.</strong> You may not assign these Terms without our written
        consent. We may assign these Terms in connection with a merger, acquisition, or sale of
        assets.
      </p>
      <p>
        13.7. <strong>Notices.</strong> We may send notices to the email associated with your
        account. You may send notices to legal@orcabot.com.
      </p>
      <p>
        13.8. <strong>Modifications.</strong> We may update these Terms at any time. Material changes
        will be communicated via email or in-product notice at least 30 days before they take effect.
        Continued use after the effective date constitutes acceptance.
      </p>

      {/* Section 14 */}
      <h2>14. Contact</h2>
      <p>For questions about these Terms, contact us at:</p>
      <p>
        Rob Macrae
        <br />
        legal@orcabot.com
      </p>
    </>
  );
}
