#!/usr/bin/env sh
set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
CONTROLPLANE_PORT=${CONTROLPLANE_PORT:-8787}
D1_SHIM_ADDR=${D1_SHIM_ADDR:-"127.0.0.1:9001"}
D1_SHIM_DEBUG=${D1_SHIM_DEBUG:-""}
FRONTEND_DIR=${FRONTEND_DIR:-"$ROOT_DIR/../frontend"}
FRONTEND_PORT=${FRONTEND_PORT:-8788}
SANDBOX_URL=${SANDBOX_URL:-"http://127.0.0.1:8080"}
SANDBOX_INTERNAL_TOKEN=${SANDBOX_INTERNAL_TOKEN:-"dev-sandbox-token"}
INTERNAL_API_TOKEN=${INTERNAL_API_TOKEN:-"dev-internal-token"}
DEV_AUTH_ENABLED=${DEV_AUTH_ENABLED:-"true"}
ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-"http://localhost:$FRONTEND_PORT"}
FRONTEND_URL=${FRONTEND_URL:-"http://localhost:$FRONTEND_PORT"}
OAUTH_REDIRECT_BASE=${OAUTH_REDIRECT_BASE:-"http://localhost:$CONTROLPLANE_PORT"}
EMAIL_FROM=${EMAIL_FROM:-"OrcaBot Desktop <noreply@localhost>"}
# Generate or reuse a 32-byte base64 key — used by AES-GCM in controlplane/crypto/secrets.ts
SECRETS_KEY_FILE="$ROOT_DIR/.dev-secrets-encryption-key"
if [ ! -f "$SECRETS_KEY_FILE" ]; then
  head -c 32 /dev/urandom | base64 > "$SECRETS_KEY_FILE"
  chmod 600 "$SECRETS_KEY_FILE"
fi
SECRETS_ENCRYPTION_KEY=${SECRETS_ENCRYPTION_KEY:-"$(cat "$SECRETS_KEY_FILE")"}

# Optional pass-through — unset feature degrades gracefully
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-""}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-""}
GOOGLE_API_KEY=${GOOGLE_API_KEY:-""}
GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID:-""}
GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET:-""}
MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID:-""}
MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET:-""}
ONEDRIVE_CLIENT_ID=${ONEDRIVE_CLIENT_ID:-""}
ONEDRIVE_CLIENT_SECRET=${ONEDRIVE_CLIENT_SECRET:-""}
BOX_CLIENT_ID=${BOX_CLIENT_ID:-""}
BOX_CLIENT_SECRET=${BOX_CLIENT_SECRET:-""}
TWITTER_CLIENT_ID=${TWITTER_CLIENT_ID:-""}
TWITTER_CLIENT_SECRET=${TWITTER_CLIENT_SECRET:-""}
DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID:-""}
DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET:-""}
SLACK_CLIENT_ID=${SLACK_CLIENT_ID:-""}
SLACK_CLIENT_SECRET=${SLACK_CLIENT_SECRET:-""}
RESEND_API_KEY=${RESEND_API_KEY:-""}
EGRESS_PROXY_ENABLED=${EGRESS_PROXY_ENABLED:-""}

cleanup() {
  if [ -n "${WORKERD_PID:-}" ]; then
    kill "$WORKERD_PID" 2>/dev/null || true
  fi
  if [ -n "${D1_PID:-}" ]; then
    kill "$D1_PID" 2>/dev/null || true
  fi
  if [ -n "${FRONTEND_PID:-}" ]; then
    kill "$FRONTEND_PID" 2>/dev/null || true
  fi
}
trap cleanup EXIT INT TERM

printf '%s\n' "Building controlplane worker bundle..."
"$ROOT_DIR/workerd/scripts/build-workerd.sh"

printf '%s\n' "Starting D1 shim..."
D1_SHIM_DEBUG="$D1_SHIM_DEBUG" \
D1_SHIM_ADDR="$D1_SHIM_ADDR" "$ROOT_DIR/d1-shim/scripts/run-d1-shim.sh" &
D1_PID=$!

printf '%s\n' "Starting workerd..."
D1_HTTP_URL="http://d1-shim" \
CONTROLPLANE_PORT="$CONTROLPLANE_PORT" \
SANDBOX_URL="$SANDBOX_URL" \
SANDBOX_INTERNAL_TOKEN="$SANDBOX_INTERNAL_TOKEN" \
INTERNAL_API_TOKEN="$INTERNAL_API_TOKEN" \
DEV_AUTH_ENABLED="$DEV_AUTH_ENABLED" \
ALLOWED_ORIGINS="$ALLOWED_ORIGINS" \
FRONTEND_URL="$FRONTEND_URL" \
D1_SHIM_DEBUG="$D1_SHIM_DEBUG" \
SECRETS_ENCRYPTION_KEY="$SECRETS_ENCRYPTION_KEY" \
OAUTH_REDIRECT_BASE="$OAUTH_REDIRECT_BASE" \
EMAIL_FROM="$EMAIL_FROM" \
GOOGLE_CLIENT_ID="$GOOGLE_CLIENT_ID" \
GOOGLE_CLIENT_SECRET="$GOOGLE_CLIENT_SECRET" \
GOOGLE_API_KEY="$GOOGLE_API_KEY" \
GITHUB_CLIENT_ID="$GITHUB_CLIENT_ID" \
GITHUB_CLIENT_SECRET="$GITHUB_CLIENT_SECRET" \
MICROSOFT_CLIENT_ID="$MICROSOFT_CLIENT_ID" \
MICROSOFT_CLIENT_SECRET="$MICROSOFT_CLIENT_SECRET" \
ONEDRIVE_CLIENT_ID="$ONEDRIVE_CLIENT_ID" \
ONEDRIVE_CLIENT_SECRET="$ONEDRIVE_CLIENT_SECRET" \
BOX_CLIENT_ID="$BOX_CLIENT_ID" \
BOX_CLIENT_SECRET="$BOX_CLIENT_SECRET" \
TWITTER_CLIENT_ID="$TWITTER_CLIENT_ID" \
TWITTER_CLIENT_SECRET="$TWITTER_CLIENT_SECRET" \
DISCORD_CLIENT_ID="$DISCORD_CLIENT_ID" \
DISCORD_CLIENT_SECRET="$DISCORD_CLIENT_SECRET" \
SLACK_CLIENT_ID="$SLACK_CLIENT_ID" \
SLACK_CLIENT_SECRET="$SLACK_CLIENT_SECRET" \
RESEND_API_KEY="$RESEND_API_KEY" \
EGRESS_PROXY_ENABLED="$EGRESS_PROXY_ENABLED" \
  "$ROOT_DIR/workerd/scripts/run-workerd.sh" &
WORKERD_PID=$!

printf '%s\n' "Initializing database..."
for _ in 1 2 3 4 5; do
  if curl -fsS "http://127.0.0.1:$CONTROLPLANE_PORT/health" >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

printf '%s\n' "Starting frontend dev server..."
(
  cd "$FRONTEND_DIR"
  NEXT_PUBLIC_API_URL="http://localhost:$CONTROLPLANE_PORT" \
  NEXT_PUBLIC_SITE_URL="http://localhost:$FRONTEND_PORT" \
  NEXT_PUBLIC_DEV_MODE_ENABLED="true" \
  NEXT_PUBLIC_DESKTOP_MODE="true" \
  npx wrangler dev -c wrangler.toml --port "$FRONTEND_PORT"
) &
FRONTEND_PID=$!

printf '%s\n' "Desktop dev stack running. Frontend + controlplane on localhost."
wait
